  <link rel="stylesheet" href="./css/dashboard.css">
  <div class="sidebar">
    <div class="logo">
      <h2>Admin Panel</h2>
    </div>
    <ul class="menu">
      <li><a href="dashboard" class="active">Dashboard</a></li>
      <li><a href="<?php echo BASE_URL ?>mostrar_formulario_computadoras/">agregar Computadoras</a></li>
      <li><a href="<?php echo BASE_URL ?>mostrar_formulario_categorias/">agregar Categorías</a></li>
      <li><a href="<?php echo BASE_URL ?>computadoras/">editar computadoras</a></li>
      <li><a href="<?php echo BASE_URL ?>home">editar categorias</a></li>
    </ul>
  </div>

  <div class="main-content">
    <header>
      <h1>Bienvenido <?php echo $user; ?></h1>
    </header>
    <section class="content">
      <h2>Seleccioná una sección del menú</h2>
    </section>
  </div>