<link rel="stylesheet" href="../css/formulario.agregar.css">
<form action="<?php echo BASE_URL ?>actualizarComputadoras/<?php echo $computadora->id ?>" method="POST" enctype="multipart/form-data">

  <h2><?php echo $computadora->modelo ?></h2>

  <label for="modelo">Modelo:</label>
  <input type="text" id="modelo" name="modelo" value="<?php echo $computadora->modelo ?>">

  <label for="descripcion">Descripción:</label>
  <textarea id="descripcion" name="descripcion"><?php echo $computadora->descripcion ?></textarea>

  <label for="precio">Precio (ARS):</label>
  <input type="number" id="precio" name="precio" value="<?php echo $computadora->precio ?>">

  <label for="gama">Gama:</label>
  <select id="gama" name="gama">
    <option value="">-- Seleccionar --</option>
    <option value="1" <?php if ($computadora->categoria_id == 1) echo 'selected'; ?>>Gaming</option>
    <option value="2" <?php if ($computadora->categoria_id == 2) echo 'selected'; ?>>Oficina</option>
    <option value="3" <?php if ($computadora->categoria_id == 3) echo 'selected'; ?>>Estudio</option>
  </select>

  <label>Imagen actual:</label>
  <img src="<?php echo $computadora->img ?>" width="200">

  <input type="hidden" name="img_actual" value="<?php echo $computadora->img ?>"> <!--guardar la información de la imagen actual, para que cuando envíes el formulario al controller, siempre tengas el valor original aunque el usuario no escriba nada nuevo -->

  <label>Nueva URL de imagen:</label>
  <input type="text" name="imagen" placeholder="link">


  <button type="submit">Guardar</button>
  <button href="dashboard">Volver</button>
</form>