  <link rel="stylesheet" href="../css/formulario.agregar.css">
  <form action="<?php echo BASE_URL ?>agregarCategorias" method="POST" enctype="multipart/form-data">
    <h2>Nuevo categoria</h2>

    <label for="categoria">categoria:</label>
    <input type="text" id="categoria" name="categoria" placeholder="gaming" required>

    <label for="descripcion">Descripción:</label>
    <textarea id="descripcion" name="descripcion" placeholder="Descripción breve..." required></textarea>

    <button type="submit">Guardar</button>
    <button href="dashboard">Volver</button>
  </form>