<link rel="stylesheet" href="css/formulario.agregar.css">
<link rel="stylesheet" href="css/estilos.css">
<link rel="stylesheet" href="css/header.css">
<style>
    #loginBtn {
        width: 100%;
        background-color: #7b2ff7;
        color: #fff;
        border: none;
        padding: 10px;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background-color 0.2s;
    }

    input:focus {
        border: 1px solid #7b2ff7;
    }

    p {
        margin-top: 15px;
        color: gray;
    }

    a {
        text-decoration: none;
        color: #7b2ff7;
    }
</style>
<form action="" method="post" style="margin: 30vh 0">
    <h2>Registrarse</h2>
    <div>
        <label for="username">Usuario</label>
        <input type="text" name="username" required>
    </div>
    <div>
        <label for="password">Contraseña</label>
        <input type="text" name="password" required>
    </div>
    <div>
        <input type="submit" value="Registrarse" id="loginBtn">
    </div>
    <div>
        <p>¿Ya tenes Cuenta? <a href="login">Inicia Sesion</a></p>
    </div>
</form>